# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leaverequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='code',
            field=models.IntegerField(unique=True),
        ),
    ]
