# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_remove_leaverequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
