# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-07 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20180207_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='leave.Status'),
            preserve_default=False,
        ),
    ]
